DROP SEQUENCE ESQUEMAPI.SEQ_NOTA_CHAMADO;

CREATE SEQUENCE ESQUEMAPI.SEQ_NOTA_CHAMADO
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP PUBLIC SYNONYM SEQ_NOTA_CHAMADO;

CREATE PUBLIC SYNONYM SEQ_NOTA_CHAMADO FOR ESQUEMAPI.SEQ_NOTA_CHAMADO;