DROP SEQUENCE ESQUEMAPI.SEQ_ARQ_CHAMADO;

CREATE SEQUENCE ESQUEMAPI.SEQ_ARQ_CHAMADO
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP PUBLIC SYNONYM SEQ_ARQ_CHAMADO;

CREATE PUBLIC SYNONYM SEQ_ARQ_CHAMADO FOR ESQUEMAPI.SEQ_ARQ_CHAMADO;