ALTER TABLE ESQUEMAPI.CHAMADO_ARQUIVO
 DROP PRIMARY KEY CASCADE;

DROP TABLE ESQUEMAPI.CHAMADO_ARQUIVO CASCADE CONSTRAINTS;

CREATE TABLE ESQUEMAPI.CHAMADO_ARQUIVO
(
  SEQ_ARQ_CHAMADO          NUMBER(5)                      NOT NULL,
  SEQ_CHAMADO       		   NUMBER (38) 					          NOT NULL,
  ANO_CHAMADO       		   NUMBER (4) 					          NOT NULL,
  NO_ARQUIVO     		       VARCHAR2(50 BYTE)              NOT NULL,
  LOCAL_ARQUIVO  		       VARCHAR2(50 BYTE)              NOT NULL,
  DTHR_INS                 DATE                           NOT NULL,
  DESCRICAO      		       VARCHAR2(255 BYTE)
)
TABLESPACE ESQUEMAPI_DAD_AUTO
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

DROP PUBLIC SYNONYM CHAMADO_ARQUIVO;

CREATE PUBLIC SYNONYM CHAMADO_ARQUIVO FOR ESQUEMAPI.CHAMADO_ARQUIVO;


ALTER TABLE ESQUEMAPI.CHAMADO_ARQUIVO ADD (
  PRIMARY KEY
  (SEQ_ARQ_CHAMADO)
  USING INDEX
    TABLESPACE ESQUEMAPI_DAD_AUTO
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE ESQUEMAPI.CHAMADO_ARQUIVO ADD (
  CONSTRAINT FK_CHAMADO_X_CHAMADO_ARQUIVO 
  FOREIGN KEY (SEQ_CHAMADO, ANO_CHAMADO) 
  REFERENCES ESQUEMAPI.CHAMADO (SEQ_CHAMADO,ANO_CHAMADO));