ALTER TABLE ESQUEMAPI.CHAMADO_NOTA
 DROP PRIMARY KEY CASCADE;

DROP TABLE ESQUEMAPI.CHAMADO_NOTA CASCADE CONSTRAINTS;

CREATE TABLE ESQUEMAPI.CHAMADO_NOTA
(
  SEQ_NOTA_CHAMADO        NUMBER(5)			NOT NULL,
  SEQ_CHAMADO       		  NUMBER (38)		NOT NULL,
  ANO_CHAMADO       		  NUMBER (4)		NOT NULL,
  DTHR_INS                DATE 				  NOT NULL,
  CD_RELATOR              VARCHAR2 (20 BYTE) NOT NULL,
  RELATO        			    VARCHAR2 (900 BYTE)
)
TABLESPACE ESQUEMAPI_DAD_AUTO
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

DROP PUBLIC SYNONYM CHAMADO_NOTA;

CREATE PUBLIC SYNONYM CHAMADO_NOTA FOR ESQUEMAPI.CHAMADO_NOTA;


ALTER TABLE ESQUEMAPI.CHAMADO_NOTA ADD (
  PRIMARY KEY
  (SEQ_NOTA_CHAMADO)
  USING INDEX
    TABLESPACE ESQUEMAPI_DAD_AUTO
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE ESQUEMAPI.CHAMADO_NOTA ADD (
  CONSTRAINT FK_CHAMADO_X_CHAMADO_NOTA 
  FOREIGN KEY (SEQ_CHAMADO, ANO_CHAMADO) 
  REFERENCES ESQUEMAPI.CHAMADO (SEQ_CHAMADO,ANO_CHAMADO));